import { describe, it, expect } from 'vitest'
import { cleanTranscript, __test } from '../../src/renderer/utils/transcriptCleaners'

describe('cleanTranscript', () => {
  it('passes through unknown extensions unchanged', () => {
    expect(cleanTranscript('notes.txt', 'hello world')).toBe('hello world')
    expect(cleanTranscript(undefined, 'plain')).toBe('plain')
  })

  describe('VTT', () => {
    it('parses <v Speaker> voice tags and formats with bold speaker labels', () => {
      const vtt = `WEBVTT

00:00:00.000 --> 00:00:03.000
<v Alice>Hello there.

00:00:03.500 --> 00:00:05.000
<v Bob>Hi Alice!`
      const out = cleanTranscript('meeting.vtt', vtt)
      expect(out).toBe('**Alice:** Hello there.\n\n**Bob:** Hi Alice!')
    })

    it('strips WEBVTT header, NOTE blocks, and cue identifiers', () => {
      const vtt = `WEBVTT
Kind: captions
Language: en

NOTE
This recording was generated by Microsoft Teams.

cue-1
00:00:00.000 --> 00:00:02.000
<v Alice>First line.

NOTE Some other note

cue-2
00:00:02.500 --> 00:00:04.000
<v Bob>Second line.`
      const out = cleanTranscript('meeting.vtt', vtt)
      expect(out).toBe('**Alice:** First line.\n\n**Bob:** Second line.')
    })

    it('merges consecutive cues from the same speaker', () => {
      const vtt = `WEBVTT

00:00:00.000 --> 00:00:02.000
<v Alice>Part one.

00:00:02.500 --> 00:00:04.000
<v Alice>Part two.

00:00:04.500 --> 00:00:06.000
<v Bob>Reply.`
      const out = cleanTranscript('meeting.vtt', vtt)
      expect(out).toBe('**Alice:** Part one. Part two.\n\n**Bob:** Reply.')
    })

    it('handles multi-line cue payloads', () => {
      const vtt = `WEBVTT

00:00:00.000 --> 00:00:05.000
<v Alice>Line one
that wraps to line two.`
      const out = cleanTranscript('meeting.vtt', vtt)
      expect(out).toBe('**Alice:** Line one that wraps to line two.')
    })

    it('falls back to plain paragraphs when there are no speaker tags', () => {
      const vtt = `WEBVTT

00:00:00.000 --> 00:00:02.000
Some narration.

00:00:02.500 --> 00:00:04.000
More narration.`
      const out = cleanTranscript('meeting.vtt', vtt)
      expect(out).toBe('Some narration.\n\nMore narration.')
    })

    it('strips residual HTML/style tags inside voice tags', () => {
      const vtt = `WEBVTT

00:00:00.000 --> 00:00:02.000
<v Alice><c.colorE5E5E5>Hello <i>world</i>.</c>`
      const out = cleanTranscript('meeting.vtt', vtt)
      expect(out).toBe('**Alice:** Hello world.')
    })

    it('decodes common HTML entities', () => {
      const vtt = `WEBVTT

00:00:00.000 --> 00:00:02.000
<v Alice>Tom &amp; Jerry &lt;3</v>`
      const out = cleanTranscript('meeting.vtt', vtt)
      expect(out).toBe('**Alice:** Tom & Jerry <3')
    })
  })

  describe('SRT', () => {
    it('parses an SRT file with inline "Speaker: text" prefixes', () => {
      const srt = `1
00:00:00,000 --> 00:00:03,000
Alice: Hello there.

2
00:00:03,500 --> 00:00:05,000
Bob: Hi Alice!`
      const out = cleanTranscript('meeting.srt', srt)
      expect(out).toBe('**Alice:** Hello there.\n\n**Bob:** Hi Alice!')
    })

    it('falls back to plain paragraphs when no inline speaker prefix', () => {
      const srt = `1
00:00:00,000 --> 00:00:03,000
some narration

2
00:00:03,500 --> 00:00:05,000
more narration`
      const out = cleanTranscript('meeting.srt', srt)
      expect(out).toBe('some narration\n\nmore narration')
    })

    it('merges consecutive same-speaker SRT cues', () => {
      const srt = `1
00:00:00,000 --> 00:00:02,000
Alice: Part one.

2
00:00:02,500 --> 00:00:04,000
Alice: Part two.`
      const out = cleanTranscript('meeting.srt', srt)
      expect(out).toBe('**Alice:** Part one. Part two.')
    })
  })

  describe('helpers', () => {
    it('extractSpeakerFromVoiceTag handles missing closing tag', () => {
      expect(__test.extractSpeakerFromVoiceTag('<v Alice>hello')).toEqual({ speaker: 'Alice', text: 'hello' })
    })

    it('extractInlineSpeakerPrefix ignores time-like prefixes', () => {
      expect(__test.extractInlineSpeakerPrefix('00:01: still talking')).toEqual({ speaker: null, text: '00:01: still talking' })
    })

    it('extractInlineSpeakerPrefix handles single-name speakers', () => {
      expect(__test.extractInlineSpeakerPrefix('Alice: hello')).toEqual({ speaker: 'Alice', text: 'hello' })
    })
  })

  it('returns the original (trimmed) text if cleaning produces nothing', () => {
    const garbage = '   not a real transcript   '
    expect(cleanTranscript('weird.vtt', garbage)).toBe('not a real transcript')
  })
})
